// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-custom-ambient-tracks.js
// Contains discovered .mp3 assets as ambient tracks.

export type CustomAmbientTrack = {
  id: string;
  url: string;
  tags: string[];
};

export const CUSTOM_AMBIENT_TRACKS: CustomAmbientTrack[] = [];
