// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/generate-sky-ground-assets.js

export type SkyGroundAsset = {
  id: string;
  url: string;
  kind: 'sky' | 'ground';
  tags: string[];
};

export const SKY_JPGS: SkyGroundAsset[] = [];

export const GROUND_JPGS: SkyGroundAsset[] = [];
